
gulp =              require 'gulp'
realFavicon =       require 'gulp-real-favicon'
fs =                require 'fs'

# File where the favicon markups are stored
FAVICON_DATA_FILE = 'faviconData.json'
# Generate the icons. This task takes a few seconds to complete.
# You should run it at least once to create the icons. Then,
# you should run it whenever RealFaviconGenerator updates its
# package (see the check-for-favicon-update task below).
gulp.task 'generate-favicon', (done) ->
  realFavicon.generateFavicon {
    masterPicture: './src/images/favicon/icon.png'
    dest: './dist/images/favicon/'
    iconsPath: '/'
    design:
      ios:
        pictureAspect: 'noChange'
        appName: 'My App Name'
      desktopBrowser: {}
      windows:
        pictureAspect: 'noChange'
        backgroundColor: '#da532c'
        onConflict: 'override'
        appName: 'My App Name'
      androidChrome:
        pictureAspect: 'noChange'
        themeColor: '#ffffff'
        manifest:
          name: 'My App Name'
          display: 'browser'
          orientation: 'notSet'
          onConflict: 'override'
          declared: true
      safariPinnedTab:
        pictureAspect: 'blackAndWhite'
        threshold: 62.5
        themeColor: '#5bbad5'
    settings:
      scalingAlgorithm: 'Mitchell'
      errorOnImageTooSmall: false
    markupFile: FAVICON_DATA_FILE
  }, ->
    done()
    return
  return

# Inject the favicon markups in your HTML pages. You should run
# this task whenever you modify a page. You can keep this task
# as is or refactor your existing HTML pipeline.
gulp.task 'inject-favicon-markups', ->
  gulp.src([ './dist/index.html' ])
  .pipe(
    realFavicon.injectFaviconMarkups(
      JSON.parse(fs.readFileSync(FAVICON_DATA_FILE)).favicon.html_code))
  .pipe gulp.dest('./dist/')
  return

# Check for updates on RealFaviconGenerator (think: Apple has just
# released a new Touch icon along with the latest version of iOS).
# Run this task from time to time. Ideally, make it part of your
# continuous integration system.
gulp.task 'check-for-favicon-update', (done) ->
  currentVersion = JSON.parse(fs.readFileSync(FAVICON_DATA_FILE)).version
  realFavicon.checkForUpdates currentVersion, (err) ->
    if err
      throw err
    return
  return

# ---
# generated by js2coffee 2.1.0
